// Single source for the plugin manifest (openclaw.plugin.json). Generated by
// scripts/sync-manifest.mjs and checked by manifest.test.ts.
import { CHANNEL_ID, WireChannelConfigSchema } from "./config.js";

export function buildManifest() {
  const schema: Record<string, unknown> = { ...WireChannelConfigSchema.schema };
  delete schema.$schema;
  return {
    id: CHANNEL_ID,
    name: "Wire",
    description: "Wire channel plugin (E2EE, MLS) built on @wireapp/wire-apps-js-sdk",
    categories: ["channels"],
    activation: { onStartup: false, onChannels: [CHANNEL_ID] },
    channels: [CHANNEL_ID],
    configSchema: { type: "object", additionalProperties: false, properties: {} },
    channelConfigs: {
      [CHANNEL_ID]: {
        label: "Wire",
        description: "End-to-end encrypted Wire conversations via a Wire app",
        schema,
        uiHints: WireChannelConfigSchema.uiHints ?? {},
      },
    },
  };
}
